### ISSUE TITLE
Error: Cannot find module '../build/Release/bson'

### ISSUE THREAD

**Issue by DiesIrae** [sergeyksv/tingodb#130]
I'm with Node 7.

```
{ Error: Cannot find module '../build/Release/bson'
    at Object.<anonymous> (/node_modules/tingodb/node_modules/bson/ext/index.js:15:10)
    at Object.<anonymous> (/node_modules/tingodb/node_modules/bson/lib/bson/index.js:3:24)
    at module.exports (/node_modules/tingodb/lib/main.js:4:40)
    at Object.<anonymous> (/server.js:33:34) code: 'MODULE_NOT_FOUND' }
```

I have the same bug as : http://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson and it can be solved by the answer http://stackoverflow.com/a/28932441/1651817 .

**Comment by mrmowgli** [comment]
I'm also with node 7, and ran into an issue installing from npm, where it fails on bson.  Looking in the node_modules/tingodb I discovered it hadn't installed it's dependencies.  I then ran `npm install` in the tingodb folder, and everything installed.  Then I went back up to the project folder and ran `npm install tingodb --save` again, and it succeeded.

**Comment by mrmowgli** [comment]
Ok, ran into issues with multiple collection.findOne requests, so I decided to try and update again, and when I did another `npm update` from within the `node_modules/tingodb` folder.

        node_modules/tingodb$ npm update
		npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
		npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
		npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

		> bson@0.2.22 install /home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb/node_modules/bson
		> (node-gyp rebuild 2> builderror.log) || (exit 0)

		make: Entering directory '/home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb/node_modules/bson/build'
		  CXX(target) Release/obj.target/bson/ext/bson.o
		bson.target.mk:92: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
		make: Leaving directory '/home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb/node_modules/bson/build'

		> kerberos@0.0.11 install /home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb/node_modules/kerberos
		> (node-gyp rebuild 2> builderror.log) || (exit 0)

		make: Entering directory '/home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb/node_modules/kerberos/build'
		  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
		kerberos.target.mk:98: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
		make: Leaving directory '/home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb/node_modules/kerberos/build'
		tingodb@0.4.2 /home/mowgli/dev/pdf_reports/pdfReports/node_modules/tingodb
		├── benchmark@1.0.0 
		├── bson@0.2.22 
		├── csv@0.3.7 
		├── lodash@3.10.1 
		├── lorem-ipsum@1.0.3 
		├── mocha@1.21.5 
		├── mongodb@1.4.40 
		├── optimist@0.6.1 
		├── safe@0.3.9 
		├── step@0.0.6 
		└── temp@0.4.0

**Comment by aemonge** [comment]
I'm having  the same issue here, but cant seam to fix it. Do you have more fixes for newer versions ?

```
Error: Cannot find module '../build/Release/bson'
Require stack:
....
  if ((this.schema.options.autoIndex) || (this.schema.options.autoIndex === null && this.db.config.autoIndex)){
                                                                                                   ^

TypeError: Cannot read property 'autoIndex' of undefined
```

node version 12.3.1
    "tingodb": "^0.6.1",
    "tungus": "0.0.5",
    "bson": "^1.0.4"


Also, this might help https://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson
