### ISSUE TITLE
ошибка при insert

### ISSUE THREAD

**Issue by wormen** [sergeyksv/tingodb#140]
после обновления ноды до версии 7.3, начали появляться ошибки вида
```
{ Error: duplicate key error index
    at tindex.set (/var/www/ivanov/data/parser_www/node_modules/tingodb/lib/tindex.js:31:10)
    at /var/www/ivanov/data/parser_www/node_modules/tingodb/lib/tcoll.js:554:8
    at /var/www/ivanov/data/parser_www/node_modules/tingodb/node_modules/lodash/index.js:3073:15
    at baseForOwn (/var/www/ivanov/data/parser_www/node_modules/tingodb/node_modules/lodash/index.js:2046:14)
    at /var/www/ivanov/data/parser_www/node_modules/tingodb/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/var/www/ivanov/data/parser_www/node_modules/tingodb/node_modules/lodash/index.js:3346:13)
    at /var/www/ivanov/data/parser_www/node_modules/tingodb/lib/tcoll.js:553:7
    at wqueue._exec (/var/www/ivanov/data/parser_www/node_modules/tingodb/lib/wqueue.js:36:3)
    at /var/www/ivanov/data/parser_www/node_modules/tingodb/lib/wqueue.js:32:9
    at wqueue.first (/var/www/ivanov/data/parser_www/node_modules/tingodb/lib/wqueue.js:11:39) errmsg: 'Error: duplicate key error index' } 
```

это при том, что код не менялся пол года, и все работало как нужно

данные вставляю так (если это интересно)

```js
let DB = require('tingodb')().Db;
global.$DB = new DB($path.join(DataDir), {
    searchInArray: true
});

let obj = { title: 'test title' };
let cn = EDB.collectionName(`district`);
$DB.collection(cn).insert(obj, (error, result)=>{
    if(error)
        console.error(`-->`, error);
    else
        console.log(`-->`, cn, result);
});
```

вероятно пора обновить библиотеку?!

**Comment by sergeyksv** [comment]
Да что то фундаметально не так на v7 - https://travis-ci.org/sergeyksv/tingodb/builds/186756496
Попробуем посмотреть на праздники

**Comment by wormen** [comment]
вероятно что-то из функционала ноды удалили

**Comment by wormen** [comment]
после обновления ноды до 7.4, проблема пропала
