### ISSUE TITLE
Escaping regex characters in regex search

### ISSUE THREAD

**Issue by ganna-shmatova** [sergeyksv/tingodb#56]
Trying to find string `/db/get/audit`:
Using search: `new RegExp('\\/db\\/get\\/audit', 'i')`
```
Testing, with string: /db/get/audit
/\/db\/get\/audit/i.test(/db/get/audit);
Result: true
```
but sending the exact same data to find it's escaping the escape characters...?
```
undefined:5
if ((/\\/db\\/get\\/audit/i).test(((obj.when && obj.when.valueOf()) ))) return
           ^
SyntaxError: Unexpected token ILLEGAL
    at tcoll.__find (C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\
lib\tcoll.js:1039:83)
    at C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\lib\tcoll.js:1
082:8
    at wqueue._exec (C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\
lib\wqueue.js:36:3)
    at C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\lib\wqueue.js:
54:10
    at process._tickCallback (node.js:419:13)
```

---

I also tried single escape but that just ignored the escapes:
Trying to find string `/db/get/audit`:
Using search: `new RegExp('\/db\/get\/audit', 'i')`
```
Testing, with string: /db/get/audit
//db/get/audit/i.test(/db/get/audit);
Result: true
```
```
undefined:6
}
^
SyntaxError: Unexpected token }
    at tcoll.__find (C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\
lib\tcoll.js:1039:83)
    at C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\lib\tcoll.js:1
082:8
    at wqueue._exec (C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\
lib\wqueue.js:36:3)
    at C:\Users\Ganna\git\AdminExtension\app\node_modules\tingodb\lib\wqueue.js:
54:10
    at process._tickCallback (node.js:419:13)
```

---

testing code:

```javascript
var find = [];

//...

searchVal = new RegExp('\/db\/get\/audit', 'i');

var test = '/db/get/audit';
console.log('\nTesting, with string: '+test);
console.log(searchVal + '.test('+test+');');
console.log('Result: ' + searchVal.test(test));

find.push({when:searchVal});

//...

collection.find({'$or': find}, {
	'skip': start,
	'limit': length,
	'sort': sort
}, function(err, cursor){
	//...
});
```

**Comment by sergeyksv** [comment]
Fixed in 0.3.5
